
export const departments = [
  { name: 'Amazonas', code: 'AMA' },
  { name: 'Antioquia', code: 'ANT' },
  { name: 'Arauca', code: 'ARA' },
  { name: 'Atlántico', code: 'ATL' },
  { name: 'Bogotá, D.C.', code: 'DC' },
  { name: 'Bolívar', code: 'BOL' },
  { name: 'Boyacá', code: 'BOY' },
  { name: 'Caldas', code: 'CAL' },
  { name: 'Caquetá', code: 'CAQ' },
  { name: 'Casanare', code: 'CAS' },
  { name: 'Cauca', code: 'CAU' },
  { name: 'Cesar', code: 'CES' },
  { name: 'Chocó', code: 'CHO' },
  { name: 'Córdoba', code: 'COR' },
  { name: 'Cundinamarca', code: 'CUN' },
  { name: 'Guainía', code: 'GUA' },
  { name: 'Guaviare', code: 'GUV' },
  { name: 'Huila', code: 'HUI' },
  { name: 'La Guajira', code: 'LAG' },
  { name: 'Magdalena', code: 'MAG' },
  { name: 'Meta', code: 'MET' },
  { name: 'Nariño', code: 'NAR' },
  { name: 'Norte de Santander', code: 'NSA' },
  { name: 'Putumayo', code: 'PUT' },
  { name: 'Quindío', code: 'QUI' },
  { name: 'Risaralda', code: 'RIS' },
  { name: 'San Andrés y Providencia', code: 'SAP' },
  { name: 'Santander', code: 'SAN' },
  { name: 'Sucre', code: 'SUC' },
  { name: 'Tolima', code: 'TOL' },
  { name: 'Valle del Cauca', code: 'VAC' },
  { name: 'Vaupés', code: 'VAU' },
  { name: 'Vichada', code: 'VID' },
];

const citiesByDepartment: Record<string, string[]> = {
    AMA: ["Leticia", "Puerto Nariño"],
    ANT: ["Medellín", "Bello", "Envigado", "Itagüí", "Sabaneta", "Rionegro", "Apartadó"],
    ARA: ["Arauca", "Saravena", "Tame"],
    ATL: ["Barranquilla", "Soledad", "Malambo", "Sabanalarga"],
    DC: ["Bogotá"],
    BOL: ["Cartagena de Indias", "Magangué", "Turbaco"],
    BOY: ["Tunja", "Duitama", "Sogamoso"],
    CAL: ["Manizales", "La Dorada", "Chinchiná"],
    CAQ: ["Florencia", "San Vicente del Caguán"],
    CAS: ["Yopal", "Aguazul", "Villanueva"],
    CAU: ["Popayán", "Santander de Quilichao"],
    CES: ["Valledupar", "Aguachica", "Agustín Codazzi"],
    CHO: ["Quibdó", "Istmina"],
    COR: ["Montería", "Cereté", "Sahagún"],
    CUN: ["Soacha", "Fusagasugá", "Facatativá", "Zipaquirá", "Chía", "Girardot"],
    GUA: ["Inírida"],
    GUV: ["San José del Guaviare"],
    HUI: ["Neiva", "Pitalito", "Garzón"],
    LAG: ["Riohacha", "Maicao", "Uribia"],
    MAG: ["Santa Marta", "Ciénaga", "Fundación"],
    MET: ["Villavicencio", "Acacías", "Granada"],
    NAR: ["Pasto", "Tumaco", "Ipiales"],
    NSA: ["Cúcuta", "Ocaña", "Pamplona"],
    PUT: ["Mocoa", "Puerto Asís", "Orito"],
    QUI: ["Armenia", "Calarcá", "Montenegro"],
    RIS: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal"],
    SAP: ["San Andrés"],
    SAN: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja"],
    SUC: ["Sincelejo", "Corozal", "Tolú"],
    TOL: ["Ibagué", "Espinal", "Melgar"],
    VAC: ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga", "Cartago"],
    VAU: ["Mitú"],
    VID: ["Puerto Carreño"],
};

export function getCitiesByDepartment(departmentCode: string): string[] | undefined {
    return citiesByDepartment[departmentCode];
}
